let products = [{
    id: 1,
    title: "Zoro",
    description: "<em>The Strawhat's Swordsman</em>",
    price: 100,
    image: "images/zoro.png",
    availableInventory: 10,
    rating: 1,
},
{
    id: 2,
    title: "Gojo",
    description: "<em>Infinite Domain Expansion</em>",
    price: 500,
    image: "images/gojo.png",
    availableInventory: 10,
    rating: 2,
},
{
    id: 3,
    title: "Kaneki",
    description: "<em>Tokyo Ghoul</em>",
    price: 1000,
    image: "images/kaneki.png",
    availableInventory: 10,
    rating: 3,
},
{
    id: 4,
    title: "Luffy",
    description: "<em>Pirate King</em>",
    price: 1500,
    image: "images/luffy.png",
    availableInventory: 15,
    rating: 4,
},
{
    id: 5,
    title: "Naruto",
    description: "<em>Lord Hokage</em>",
    price: 2000,
    image: "images/naruto.png",
    availableInventory: 20,
    rating: 4,
},
]